include ~/.cache/wal/colors-kitty.conf

# --- Fonts ---
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# --- Colors ---
background       #1e1e1e
foreground       #dcdccc

# --- Transparency & Blur ---
background_opacity 0.65
background_blur    2
# Note: background_blur works on macOS and some Linux window managers (KDE, Hyprland)
# If on Linux (GNOME/i3), you might need a compositor like 'picom' for the blur effect.
